# Generated by Django 4.2.1 on 2023-06-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Listings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
